### ISSUE TITLE
docker-compose up not reading .env parameters

### ISSUE THREAD

**Issue by zebrassimo** [veryacademy/YT_FastAPI_Celery_Redis_Flower_Introduction#1]
Hi thanks for the great tutorial!

In my docker-compose.yml, this would not work (https://youtu.be/mcX_4EvYka4?t=1067):
```
celery_worker:
    container_name: celery_worker
    build: ./main
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    command: celery -A celery_worker.celery worker --loglevel=info 
    volumes:
      - ./main/projects:/app
    depends_on:
      - redis
      - [...]
```
resulting in
```
-------------- celery@ed960d6ff0fe v5.2.3 (dawn-chorus)
celery_worker      | --- ***** ----- 
celery_worker      | -- ******* ---- Linux-5.10.76-linuxkit-aarch64-with-glibc2.31 2022-02-13 13:36:02
celery_worker      | - *** --- * --- 
celery_worker      | - ** ---------- [config]
celery_worker      | - ** ---------- .> app:         celery_worker:0xffffb6a28070
celery_worker      | - ** ---------- .> transport:   amqp://guest:**@localhost:5672//
celery_worker      | - ** ---------- .> results:     disabled://
celery_worker      | - *** --- * --- .> concurrency: 5 (prefork)
celery_worker      | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
celery_worker      | --- ***** ----- 
celery_worker      |  -------------- [queues]
celery_worker      |                 .> celery           exchange=celery(direct) key=celery

```
However, removing the environment section will work:
```
celery_worker:
    container_name: celery_worker
    build: ./main
    command: celery -A celery_worker.celery worker --loglevel=info 
    volumes:
      - ./main/projects:/app
    depends_on:
      - redis
      - [...]
```
resulting in:
```
celery_worker      |  -------------- celery@f6ab652b725c v5.2.3 (dawn-chorus)
celery_worker      | --- ***** ----- 
celery_worker      | -- ******* ---- Linux-5.10.76-linuxkit-aarch64-with-glibc2.31 2022-02-13 13:44:25
celery_worker      | - *** --- * --- 
celery_worker      | - ** ---------- [config]
celery_worker      | - ** ---------- .> app:         celery_worker:0xffffa8d40070
celery_worker      | - ** ---------- .> transport:   redis://redis:6379/0
celery_worker      | - ** ---------- .> results:     redis://redis:6379/0
celery_worker      | - *** --- * --- .> concurrency: 5 (prefork)
celery_worker      | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
celery_worker      | --- ***** ----- 
celery_worker      |  -------------- [queues]
celery_worker      |                 .> celery           exchange=celery(direct) key=celery
```
So it seems the values ${CELERY_BROKER_URL} and ${CELERY_RESULT_BACKEND} won't be populated. Any idea why?
